### ISSUE TITLE
Cannot Browse Replays

### ISSUE THREAD

**Issue by IoannisTM** [gregstein/DE-Replays-Manager#1]
Hello,
Just downloaded the latest version. When trying to browse the saved games, I have no profile listed and no games either.
When clicking the open explorer button, I get an error message
"Unhandled exception has occurred in the application.... Cannot start process because a file name has not been provided"
Below are the Details of the message

It seems to be trying to access something under 
"E:\Git\Krypton\Source\Krypton Components\ComponentFactory.Krypton.Toolkit\Controls Toolkit\KryptonButton.cs"
which I certainly do not have, since no drive E is present.

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.InvalidOperationException: Cannot start process because a file name has not been provided.
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(String fileName)
   at DEReplaysManager.Form1.d(Object , EventArgs )
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at ComponentFactory.Krypton.Toolkit.KryptonButton.OnClick(EventArgs e) in E:\Git\Krypton\Source\Krypton Components\ComponentFactory.Krypton.Toolkit\Controls Toolkit\KryptonButton.cs:line 646
   at ComponentFactory.Krypton.Toolkit.KryptonButton.OnButtonClick(Object sender, MouseEventArgs e) in E:\Git\Krypton\Source\Krypton Components\ComponentFactory.Krypton.Toolkit\Controls Toolkit\KryptonButton.cs:line 763
   at ComponentFactory.Krypton.Toolkit.ButtonController.OnClick(MouseEventArgs e) in E:\Git\Krypton\Source\Krypton Components\ComponentFactory.Krypton.Toolkit\Controller\ButtonController.cs:line 912
   at ComponentFactory.Krypton.Toolkit.ButtonController.MouseUp(Control c, Point pt, MouseButtons button) in E:\Git\Krypton\Source\Krypton Components\ComponentFactory.Krypton.Toolkit\Controller\ButtonController.cs:line 436
   at ComponentFactory.Krypton.Toolkit.ViewBase.MouseUp(Point pt, MouseButtons button) in E:\Git\Krypton\Source\Krypton Components\ComponentFactory.Krypton.Toolkit\View Base\ViewBase.cs:line 522
   at ComponentFactory.Krypton.Toolkit.ViewBase.MouseUp(Point pt, MouseButtons button) in E:\Git\Krypton\Source\Krypton Components\ComponentFactory.Krypton.Toolkit\View Base\ViewBase.cs:line 527
   at ComponentFactory.Krypton.Toolkit.ViewBase.MouseUp(Point pt, MouseButtons button) in E:\Git\Krypton\Source\Krypton Components\ComponentFactory.Krypton.Toolkit\View Base\ViewBase.cs:line 527
   at ComponentFactory.Krypton.Toolkit.ViewBase.MouseUp(Point pt, MouseButtons button) in E:\Git\Krypton\Source\Krypton Components\ComponentFactory.Krypton.Toolkit\View Base\ViewBase.cs:line 527
   at ComponentFactory.Krypton.Toolkit.ViewManager.MouseUp(MouseEventArgs e, Point rawPt) in E:\Git\Krypton\Source\Krypton Components\ComponentFactory.Krypton.Toolkit\View Base\ViewManager.cs:line 511
   at ComponentFactory.Krypton.Toolkit.VisualControlBase.OnMouseUp(MouseEventArgs e) in E:\Git\Krypton\Source\Krypton Components\ComponentFactory.Krypton.Toolkit\Controls Visuals\VisualControlBase.cs:line 968
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at ComponentFactory.Krypton.Toolkit.VisualControlBase.WndProc(Message& m) in E:\Git\Krypton\Source\Krypton Components\ComponentFactory.Krypton.Toolkit\Controls Visuals\VisualControlBase.cs:line 1195
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4300.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
DeReplaysManager
    Assembly Version: 1.3.2.0
    Win32 Version: 1.3.2.0
    CodeBase: file:///C:/Users/ioann/AppData/Roaming/DEReplaysManager/DeReplaysManager.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4270.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4300.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
DevComponents.DotNetBar2
    Assembly Version: 14.1.0.37
    Win32 Version: 1.3.2.0
    CodeBase: file:///C:/Users/ioann/AppData/Roaming/DEReplaysManager/DeReplaysManager.exe
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4300.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
ComponentFactory.Krypton.Toolkit
    Assembly Version: 4.5.0.0
    Win32 Version: 1.3.2.0
    CodeBase: file:///C:/Users/ioann/AppData/Roaming/DEReplaysManager/DeReplaysManager.exe
----------------------------------------
 

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by gregstein** [comment]
Hello,

a couple of things to check:
**Part 1**

Press Windows button  + R then type in that run box: `%userprofile%\Games\Age of Empires 2 DE`

You should see one folder or few with random digits e.g.
![folders](https://user-images.githubusercontent.com/16618729/104050208-8f186280-51e6-11eb-838a-f9ab5fa7bafe.jpg)

Whether you have one or multiple folders you need to enter each one of them and make sure they look like this:

![folder_random1](https://user-images.githubusercontent.com/16618729/104050502-02ba6f80-51e7-11eb-9645-4e42ce244daf.jpg)

Then inside each \profile\ folder something like this
![folder3](https://user-images.githubusercontent.com/16618729/104050684-44e3b100-51e7-11eb-8110-20aa6a786533.jpg)

If something is not right you can simply run DE go to options > Hotkeys and rename your hotkey profile so you DE manager identifies it with that name but most importantly regenerates and repairs missing hotkey files.

**Part 2**

Make sure DE Replays Manager installation folder contains "Updater.exe" & "string.exe"
![de-install](https://user-images.githubusercontent.com/16618729/104051227-1b775500-51e8-11eb-8988-1984a5aa4bec.jpg)

Keep me updated <3

**Comment by IoannisTM** [comment]
Hi gregstein, thanks for the reply.
 to part one.
In that folder i had only 2 files
'AdditionalOptions.aop and Player.nfp'

It seems to be working as soon as i created a new hotkey profile or just renamed the existing one.
I am not sure why but it works 
Thanks

**Comment by gregstein** [comment]
> Hi gregstein, thanks for the reply.
> to part one.
> In that folder i had only 2 files
> 'AdditionalOptions.aop and Player.nfp'
> 
> It seems to be working as soon as i created a new hotkey profile or just renamed the existing one.
> I am not sure why but it works
> Thanks

It must be a wrong reference to .hki file in 'Player.nfp'. Once you renamed your profile, the .hki file is renamed relatively and reference to it, is updated too within 'Player.nfp'.
